{% set version = "0.2.12" %}

package:
  name: wcwidth
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/w/wcwidth/wcwidth-{{ version }}.tar.gz
  sha256: f01c104efdf57971bcb756f054dd58ddec5204dd15fa31d6503ea57947d97c02

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8

test:
  imports:
    - wcwidth
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jquast/wcwidth
  license: MIT
  license_file: LICENSE
  summary: Measures number of Terminal column cells of wide-character codes.

extra:
  recipe-maintainers:
    - ocefpaf
