{% set version = "0.2.2" %}

package:
  name: wcwidth
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/w/wcwidth/wcwidth-{{ version }}.tar.gz
  sha256: 3de2e41158cb650b91f9654cbf9a3e053cee0719c9df4ddc11e4b568669e9829

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  imports:
    - wcwidth
    - wcwidth.tests

about:
  home: https://github.com/jquast/wcwidth
  license: MIT
  license_file: LICENSE.txt
  summary: Measures number of Terminal column cells of wide-character codes.

extra:
  recipe-maintainers:
    - ocefpaf
