{% set version = "0.2.9" %}

package:
  name: wcwidth
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/w/wcwidth/wcwidth-{{ version }}.tar.gz
  sha256: a675d1a4a2d24ef67096a04b85b02deeecd8e226f57b5e3a72dbb9ed99d27da8

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - backports.functools_lru_cache

test:
  imports:
    - wcwidth
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jquast/wcwidth
  license: MIT
  license_file: LICENSE
  summary: Measures number of Terminal column cells of wide-character codes.

extra:
  recipe-maintainers:
    - ocefpaf
