{% set version = "0.2.4" %}

package:
  name: wcwidth
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/w/wcwidth/wcwidth-{{ version }}.tar.gz
  sha256: 8c6b5b6ee1360b842645f336d9e5d68c55817c26d3050f46b235ef2bc650e48f

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python
    - pip
  run:
    - python
    - backports.functools_lru_cache

test:
  imports:
    - wcwidth
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jquast/wcwidth
  license: MIT
  license_file: LICENSE
  summary: Measures number of Terminal column cells of wide-character codes.

extra:
  recipe-maintainers:
    - ocefpaf
