schema_version: 1

context:
  version: "0.8.5"

package:
  name: wcwidth
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/w/wcwidth/wcwidth-${{ version }}.tar.gz
  sha256: 720336056169eac7744c5a84165d563cc6f569652615071cbfd575f131e7537f

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - wcwidth
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: Measures the displayed width of unicode strings in a terminal
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/jquast/wcwidth

extra:
  recipe-maintainers:
    - ocefpaf
