schema_version: 1

context:
  version: "0.8.4"

package:
  name: wcwidth
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/w/wcwidth/wcwidth-${{ version }}.tar.gz
  sha256: 2dae09efa25253ae2874188e86d6861af3b1652aef4118cdf3f0bda288a957fb

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - wcwidth
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: Measures the displayed width of unicode strings in a terminal
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/jquast/wcwidth

extra:
  recipe-maintainers:
    - ocefpaf
