travis:
  secure:
    BINSTAR_TOKEN: bDigibMf7hIhQT5sLqmtbyCuvz5j6HkbBnH7+2XiuWIcl46/peYTucS6nom7mL1qj0+PwkvUoLNMqTyDhtwm4slu1nOxn2zZvhLPptSpxf1qtp7mWtKeemmnf3AL+JGnibkSjykdZr+Sl0qYF3CujEQCe85W7eyVqdTlFLj6myNl0AfV4i2vnPfVTgoAOFaSfBydjirPmlsNY0QiGbVVL7F4LYBPwTktfxsRzAILvhYYNOAzyRUehlPhX8w7Od4KBNXo07LcYxQyynfxNSGSs3ShRHxjZxTsKo3ixo6a1MV7saK4EWoafS8jztE3FBesRvO/lKya0Ahtd1aNOg680XhXcr4h4sBys0x6vFTlDVQdO509H0yrJ+4kO9xVcGb0mZh/jDMz65VjyBwRKaO9gb4no7LRtTEGwcxZfp8yZ4YQRHXbKEuujk2+iis5TRglwfZtlFTHL38gqtTLoYcIOLQ4aq04pJy3Wk6yKjdc0Ydet5ikWkvRILrARFonEkyQtz3YHMoz3plhyYWpbILLqqDe/OBAsD7Dj6vbFy7TnJ2QsmyaA5QXjiBuY8YHEbUlfnotnFbRzZNwuNxZAobQ6N0nSe+sEqxE66cKcM0YU0V5E4FhA+qfmO/CXp/HQWFuZ8yomw643F+s4eXyI7uTaRXBCmhrnm0VjHXcpel71lg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
